require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new :spec

require 'rubocop/rake_task'
RuboCop::RakeTask.new :rubocop do |t|
  t.options = ['lib/*.rb', '--config=../.rubocop.yml']
end

task default: [:spec, :rubocop]
